{% set name = "napari-simpleannotate" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2d9d4d5f93dd1fc027163d05f7a7ed5a8ae70fafc596a91a704de9b641acb97a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=42.0.0
    - wheel
  run:
    - numpy
    - magicgui
    - python >={{ python_min }}
    - pyyaml
    - qtpy
    - scikit-image

test:
  imports:
    - napari_simpleannotate
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-simpleannotate
  summary: A simple plugin to label image
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/hiroalchem/napari-simpleannotate

extra:
  recipe-maintainers:
    - goanpeca
    - hiroalchem
    - jaimergp
