{% set name = "napari-simpleannotate" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-simpleannotate-{{ version }}.tar.gz
  sha256: 08bba922f7c5ec6243f4ec13b06d099814d7ee03c2c9986de9352081effe4ca5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42.0.0
    - wheel
  run:
    - numpy
    - magicgui
    - python >=3.8
    - pyyaml
    - qtpy
    - scikit-image

test:
  imports:
    - napari_simpleannotate
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-simpleannotate
  summary: A simple plugin to label image
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/hiroalchem/napari-simpleannotate

extra:
  recipe-maintainers:
    - goanpeca
    - hiroalchem
    - jaimergp
